version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./media:/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=estate_shop
      - POSTGRES_PASSWORD=estate_shop
      - POSTGRES_DB=estate_shop

volumes:
  postgres_data:
