# Generated by Django 3.2.8 on 2021-10-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('property_type', models.CharField(blank=True, choices=[('Land house', 'Land house'), ('Apartment', 'Apartment')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Sold', 'Sold')], max_length=10)),
                ('area', models.FloatField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('garage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('estate_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.estate')),
            ],
        ),
    ]
