# Generated by Django 3.2.8 on 2021-10-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_estate_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='user.png', upload_to='estates'),
        ),
    ]
