# Generated by Django 3.2.8 on 2021-10-29 08:59

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 29, 8, 21, 44, 625356, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='main_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='estates'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(null=True, upload_to='estates'),
        ),
    ]
