# Generated by Django 3.2.8 on 2021-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_auto_20211029_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='status',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Sold', 'Sold'), ('Rent', 'Rent')], max_length=10),
        ),
    ]
