# Generated by Django 3.2.8 on 2021-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0005_alter_estate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
